version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "3001:3001"
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/PayFlex
      - NODE_ENV=development
    volumes:
      - ./backend:/app-backend
      - /app-backend/node_modules
    container_name: payFlex_backend
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=PayFlex
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  db-data: